CREATE TABLE IF NOT EXISTS hubs (
    id SERIAL PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ALTER TABLE hubs 
-- ADD CONSTRAINT fk_hubs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;